stages:
  - test
  - build-and-push

variables:
  REGISTRY: acrknowledgehub570863.azurecr.io
  IMAGE_NAME: monitoring-web

# Stage 1: Run Python Unit Tests
test_python:
  stage: test
  image: python:3.11-slim
  script:
    - apt-get update && apt-get install -y gcc unixodbc freetds-dev curl gnupg2 apt-transport-https ca-certificates g++ unixodbc-dev
    - curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
    - curl -fsSL https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list
    - apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18
    - pip install --upgrade pip
    - pip install -r monitoring-web/requirements.txt
    - pip install pytest pytest-cov
    - export PYTHONPATH=./monitoring-web
    - cd monitoring-web
    - pytest tests/ --cov=app --cov-report=xml
  only:
    changes:
      - monitoring-web/**/*
      - .gitlab-ci.yml

# Stage 2: Build Docker Image and Push to Azure Container Registry
build_and_push_docker:
  stage: build-and-push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # Login to Azure Container Registry
    - docker login $REGISTRY -u $ACR_USERNAME -p $ACR_PASSWORD
  script:
    - cd monitoring-web
    - docker build --no-cache -t $REGISTRY/$IMAGE_NAME:latest -t $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $REGISTRY/$IMAGE_NAME:latest
    - docker push $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
  only:
    refs:
      - main
    changes:
      - monitoring-web/**/*
      - .gitlab-ci.yml
